# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.0

    - name: mise action
      # You may pin to the exact commit or the version.
      # uses: jdx/mise-action@3bc85396a273ed82bba5e53a15174bbf9dba095c
      uses: jdx/mise-action@v2.0.2

    - name: Set up Go
      uses: actions/setup-go@v6.5.0
      with:
        go-version: '1.26'

    - name: Cache
      uses: actions/cache@v5.1.0
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: "<path>"
    # An explicit key for restoring and saving the cache
        key: "xskills-cache"     
    
    - name: Test
      run: go test -v ./...
    
    - name: Build
      run: go build -v ./...
